### PR TITLE
add BVV

### PR DESCRIPTION
**Pull request by l-with**

### CODE REVIEW

**Comment by coderbyheart** [comment]
Is there some additional information that shows that they support working remote?

Because I've reviewed https://www.bvv.de/ueber-den-bvv/karriere/ and https://www.bvv.de/ueber-den-bvv/karriere/lp_senior_backend_entwickler_wmd.html and could not find anything related to that.

**Comment by coderbyheart** [comment]
Is there some additional information that shows that they support working remote?

Because I've reviewed https://www.bvv.de/ueber-den-bvv/karriere/ and https://www.bvv.de/ueber-den-bvv/karriere/lp_senior_backend_entwickler_wmd.html and could not find anything related to that.

**Comment by coderbyheart** [comment]
Is there some additional information that shows that they support working remote?

Because I've reviewed https://www.bvv.de/ueber-den-bvv/karriere/ and https://www.bvv.de/ueber-den-bvv/karriere/lp_senior_backend_entwickler_wmd.html and could not find anything related to that.

**Comment by l-with** [comment]
I'll iniate that the information is added.

**Comment by danielbayerlein** [comment]
@l-with Is it possible to work completely remotely?

**Comment by l-with** [comment]
> @l-with Is it possible to work completely remotely?

no, but nearly: there are team events that are not very smart in hybrid mode

**Review by danielbayerlein — APPROVED** [review]

**Pull request merged**
