### PR TITLE
Added new company: bilstein group

### PR DESCRIPTION
**Pull request by bilstein-group**
Added german remote company bilstein group
( https://bilsteingroup.com/en )

The bilstein group is global acting supplier and manufacturer for automotive spare parts. It's well known for its innovative digital solutions in the IAM sector. Software developer teams work remotely together.

Disclaimer: I'm working as a SWE for this company. In case you have any questions towards our team, culture, jobs or remote offerings, let me know.

### CODE REVIEW

**Comment by UnderTheCraft** [comment]
That's what I call a nice way of talent attraction 😄

**Comment by bilstein-group** [comment]
Hi @danielbayerlein  ,

do you need any further information or may I help in any other way?

**Comment by danielbayerlein** [comment]
@bilstein-group I overlooked the PR. Sorry!

**Comment by bilstein-group** [comment]
Thanks for merging. :-)

**Pull request merged**
