### PR TITLE
Add Taledo to the list

### PR DESCRIPTION
**Pull request by amit-choudhary**

### CODE REVIEW

**Comment by danielbayerlein** [comment]
@amit-choudhary Is Taledo a remote friendly company?

**Comment by coderbyheart** [comment]
Well, all of their own job posts mention ability for homeoffice, and some jobs are fully remote.
https://app.taledo.com/taledo/jobs/frontend-developer-m-w-d-job-nnkmjq

**Comment by coderbyheart** [comment]
On a side note, I was also a bit wary about adding a recruiting company, I'd like it if this list is not adding remote jobs boards or companies that recruite for remote jobs.

**Comment by coderbyheart** [comment]
@amit-choudhary why did you close it?

**Pull request closed without merging**
