### PR TITLE
Add dkd

### PR DESCRIPTION
**Pull request by saitho**

### CODE REVIEW

**Comment by danielbayerlein** [comment]
Thank you!

**Comment by dvogt23** [comment]
website is down @saitho

**Comment by saitho** [comment]
> website is down @saitho 

Works fine for me 🤔

**Comment by spotlesscoder** [comment]
any idea why all lines have been changed? 
In case it's the newlines format - I suggest the old newline format is kept.
A commit should not contain unnecessary changes - or at least reformatting should be a separate commit to keep the history useful ;)

**Comment by saitho** [comment]
So Markdown table rows are flush in markup ;)

spotlesscoder ***@***.***> schrieb am Fr., 20. Dez. 2024,
16:47:

**Pull request merged**
